// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKW7h33aFFiyviDX8xnJZcK9l3m1UB2YQ',
    appId: '1:770735993850:web:a71e7c80c1f99ff4a82a43',
    messagingSenderId: '770735993850',
    projectId: 'gateon-f45cd',
    authDomain: 'gateon-f45cd.firebaseapp.com',
    storageBucket: 'gateon-f45cd.firebasestorage.app',
    measurementId: 'G-ZSH09ZW8RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSGYZbKEZSNMNwOvvcluep2yN_rLlMdUk',
    appId: '1:770735993850:android:36c290439417dceda82a43',
    messagingSenderId: '770735993850',
    projectId: 'gateon-f45cd',
    storageBucket: 'gateon-f45cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlx7TzkeeEXcHdnNK919sA9fNVJEG3_X0',
    appId: '1:770735993850:ios:6079f8e2d0a7791ca82a43',
    messagingSenderId: '770735993850',
    projectId: 'gateon-f45cd',
    storageBucket: 'gateon-f45cd.firebasestorage.app',
    iosBundleId: 'com.laonstory.mguardApp',
  );

}