// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'dart:async';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return web;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhNkg7pt4dGRF-T2b65O3R2BlmK5Zf00k',
    appId: '1:842752158199:android:7179e49ec6225f877da6f2',
    messagingSenderId: '842752158199',
    projectId: 'laonstory-m-guard',
    storageBucket: 'laonstory-m-guard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC10GyYA2fQQGfZG71srQKGvM7-aFr1ktQ',
    appId: '1:842752158199:ios:1e927ecb8ef850727da6f2',
    messagingSenderId: '842752158199',
    projectId: 'laonstory-m-guard',
    storageBucket: 'laonstory-m-guard.appspot.com',
    iosClientId: '842752158199-0rg2t1qp9be8oudi2ml5al10pv7juer0.apps.googleusercontent.com',
    iosBundleId: 'com.laonstory.mguardApp',
  );

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'fwaefwfwfff',
    appId: '1:842752158199:ios:1e927ecb8ef850727da6f2',
    messagingSenderId: '842752158199',
    projectId: 'laonstory-m-guard',
    storageBucket: 'laonstory-m-guard.appspot.com',
    iosClientId: '842752158199-0rg2t1qp9be8oudi2ml5al10pv7juer0.apps.googleusercontent.com',
    iosBundleId: 'com.laonstory.mguardApp',
  );
}

/// A notification action which triggers a url launch event
const String urlLaunchActionId = 'id_1';

/// A notification action which triggers a App navigation event
const String navigationActionId = 'id_3';

/// Defines a iOS/MacOS notification category for text input actions.
const String darwinNotificationCategoryText = 'textCategory';

/// Defines a iOS/MacOS notification category for plain actions.
const String darwinNotificationCategoryPlain = 'plainCategory';

class ReceivedNotification {
  ReceivedNotification({
    required this.id,
    required this.title,
    required this.body,
    required this.payload,
  });

  final int id;
  final String? title;
  final String? body;
  final String? payload;
}

/// Streams are created so that app can respond to notification-related events
/// since the plugin is initialised in the `main` function
final StreamController<ReceivedNotification> didReceiveLocalNotificationStream = StreamController<ReceivedNotification>.broadcast();
